default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: port_analy_dev

test:
  <<: *default
  database: port_analy_test

production:
  <<: *default
  database: port_analy_production
  username: port_analy
  password: <%= ENV['PORT_ANALY_DATABASE_PASSWORD'] %>
