# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a818a8abdc06a4de13b1bda53b4ba7424e01ee3ce4b431dadaa5b5eb4d603a157228e49d3f3e50aa20bd660befc100090f32c69a88a5ea3edadd94b57642c5c3

test:
  secret_key_base: 7e52bce71400405c523bf1914b190b0486452139af5d2c644bbd8bae7e68f43b2d9ca8e93530471a730ec81e41fd5bda712d122810a5bbfe283a73b40f3d3a59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
